'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_cajachica
        
        Public  Property Tipo As Integer
        
        '
        Public  Property idcajadinero As Nullable(of Integer)
        
        '
        Public  Property idusuarios As Nullable(of Integer)
        
        '
        Public  Property fecha As String

        '
        Public Property fechaInicio As String

        '
        Public Property fechaFinal As String

        '
        Public  Property montoinicio As Decimal
        
        '
        Public  Property montofinal As Decimal
        
        '
        Public  Property comentario As String
        
        Public Sub New()
            
        End Sub

        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _idcajadinero As Integer, ByVal _idusuarios As Integer, ByVal _fecha As String, ByVal _fechaInicio As String, ByVal _fechaFinal As String, ByVal _montoinicio As Decimal, ByVal _montofinal As Decimal, ByVal _comentario As String)

            Tipo = _Tipo
            idcajadinero = _idcajadinero
            idusuarios = _idusuarios
            fecha = _fecha
            fechaInicio = _fechaInicio
            fechaFinal = _fechaFinal
            montoinicio = _montoinicio
            montofinal = _montofinal
            comentario = _comentario
        End Sub
    End Class
End Namespace
