'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_dinero
        
        Public  Property Tipo As Integer
        
        '
        Public  Property iddinero As Nullable(of Integer)
        
        '
        Public  Property idusuarios As Nullable(of Integer)

        '
        Public Property idventas As Nullable(Of Integer)

        'C compra
        'V venta
        Public Property compraventa As String

        '
        Public Property fechahora As Date

        'E efectivo
        'Q qr
        Public  Property tipopago As String
        
        '
        Public  Property monto As Decimal
        
        Public Sub New()
            
        End Sub

        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _iddinero As Integer, ByVal _idusuarios As Integer, ByVal _idventas As Integer, ByVal _compraventa As String, ByVal _fechahora As Date, ByVal _tipopago As String, ByVal _monto As Decimal)

            Tipo = _Tipo
            iddinero = _iddinero
            idusuarios = _idusuarios
            idventas = _idventas
            compraventa = _compraventa
            fechahora = _fechahora
            tipopago = _tipopago
            monto = _monto
        End Sub
    End Class
End Namespace
