'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_detalleventas
        
        Public  Property Tipo As Integer
        
        '
        Public  Property ventas_idventas As Nullable(of Integer)
        
        '
        Public  Property producto_idproducto As Nullable(of Integer)
        
        '
        Public  Property cantidad As Decimal
        
        '
        Public  Property precio As Decimal
        
        '
        Public  Property total As Decimal
        
        Public Sub New()
            
        End Sub
        
        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _ventas_idventas As Integer, ByVal _producto_idproducto As Integer, ByVal _cantidad As Decimal, ByVal _precio As Decimal, ByVal _total As Decimal)
            
            Tipo = _Tipo
            ventas_idventas = _ventas_idventas
            producto_idproducto = _producto_idproducto
            cantidad = _cantidad
            precio = _precio
            total = _total
        End Sub
    End Class
End Namespace
