'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_empresa
        
        Public  Property Tipo As Integer
        
        '
        Public  Property idempresa As Nullable(of Integer)
        
        '
        Public  Property ruc As String
        
        '
        Public  Property razonsocial As String
        
        '
        Public  Property titulo As String
        
        '
        Public  Property direccion As String
        
        '
        Public  Property telefono As String
        
        '
        Public  Property correo As String
        
        '
        Public  Property paginaweb As String
        
        '
        Public  Property ubigeo As String
        
        '
        Public  Property piepagina As String
        
        Public Sub New()
            
        End Sub
        
        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _idempresa As Integer, ByVal _ruc As String, ByVal _razonsocial As String, ByVal _titulo As String, ByVal _direccion As String, ByVal _telefono As String, ByVal _correo As String, ByVal _paginaweb As String, ByVal _ubigeo As String, ByVal _piepagina As String)
            
            Tipo = _Tipo
            idempresa = _idempresa
            ruc = _ruc
            razonsocial = _razonsocial
            titulo = _titulo
            direccion = _direccion
            telefono = _telefono
            correo = _correo
            paginaweb = _paginaweb
            ubigeo = _ubigeo
            piepagina = _piepagina
        End Sub
    End Class
End Namespace
