'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_mesa
        
        Public  Property Tipo As Integer
        
        '
        Public  Property idmesa As Nullable(of Integer)
        
        '
        Public  Property nombre As String
        
        '
        Public  Property descripcion As String
        
        '
        Public  Property fecreg As Date
        
        '
        Public  Property fecmod As Date
        
        Public Sub New()
            
        End Sub
        
        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _idmesa As Integer, ByVal _nombre As String, ByVal _descripcion As String, ByVal _fecreg As Date, ByVal _fecmod As Date)
            
            Tipo = _Tipo
            idmesa = _idmesa
            nombre = _nombre
            descripcion = _descripcion
            fecreg = _fecreg
            fecmod = _fecmod
        End Sub
    End Class
End Namespace
