'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_pedido
        
        Public  Property Tipo As Integer
        
        '
        Public  Property idpedido As Nullable(of Integer)
        
        '
        Public  Property idmesa As Nullable(of Integer)
        
        '
        Public  Property idusuarios As Nullable(of Integer)
        
        '
        Public  Property numero As Nullable(of Integer)
        
        '
        Public  Property total As Decimal
        
        '
        Public  Property fechahora As Date
        
        '
        Public  Property estado As Nullable(of Integer)
        
        Public Sub New()
            
        End Sub
        
        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _idpedido As Integer, ByVal _idmesa As Integer, ByVal _idusuarios As Integer, ByVal _numero As Integer, ByVal _total As Decimal, ByVal _fechahora As Date, ByVal _estado As Integer)
            
            Tipo = _Tipo
            idpedido = _idpedido
            idmesa = _idmesa
            idusuarios = _idusuarios
            numero = _numero
            total = _total
            fechahora = _fechahora
            estado = _estado
        End Sub
    End Class
End Namespace
