'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_personas
        
        Public  Property Tipo As Integer
        
        '
        Public  Property idpersonas As Nullable(of Integer)
        
        '
        Public  Property dni As String
        
        '
        Public  Property nombre As String
        
        '
        Public  Property apellidos As String
        
        '
        Public  Property celular As String
        
        '
        Public  Property correo As String
        
        '
        Public  Property direccion As String
        
        '
        Public  Property fecreg As Date
        
        '
        Public  Property fecmod As Date
        
        Public Sub New()
            
        End Sub
        
        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _idpersonas As Integer, ByVal _dni As String, ByVal _nombre As String, ByVal _apellidos As String, ByVal _celular As String, ByVal _correo As String, ByVal _direccion As String, ByVal _fecreg As Date, ByVal _fecmod As Date)
            
            Tipo = _Tipo
            idpersonas = _idpersonas
            dni = _dni
            nombre = _nombre
            apellidos = _apellidos
            celular = _celular
            correo = _correo
            direccion = _direccion
            fecreg = _fecreg
            fecmod = _fecmod
        End Sub
    End Class
End Namespace
