'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_productostock
        
        Public  Property Tipo As Integer
        
        '
        Public  Property idproductostock As Nullable(of Integer)
        
        '
        Public  Property idproducto As Nullable(of Integer)
        
        '
        Public  Property idusuarios As Nullable(of Integer)
        
        '
        Public  Property fechahora As Date
        
        '
        Public  Property entrada As Decimal
        
        '
        Public  Property salida As Decimal
        
        '
        Public  Property total As Decimal
        
        '
        Public  Property comentario As String
        
        Public Sub New()
            
        End Sub
        
        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _idproductostock As Integer, ByVal _idproducto As Integer, ByVal _idusuarios As Integer, ByVal _fechahora As Date, ByVal _entrada As Decimal, ByVal _salida As Decimal, ByVal _total As Decimal, ByVal _comentario As String)
            
            Tipo = _Tipo
            idproductostock = _idproductostock
            idproducto = _idproducto
            idusuarios = _idusuarios
            fechahora = _fechahora
            entrada = _entrada
            salida = _salida
            total = _total
            comentario = _comentario
        End Sub
    End Class
End Namespace
