'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_producto
        
        Public  Property Tipo As Integer
        
        '
        Public  Property idproducto As Nullable(of Integer)
        
        '
        Public  Property idunidadmedida As String
        
        '
        Public  Property idcategoria As Nullable(of Integer)
        
        '
        Public  Property idusuarios As Nullable(of Integer)
        
        '
        Public  Property nombre As String
        
        '
        Public  Property precio1 As Decimal
        
        '
        Public  Property precio2 As Decimal
        
        '
        Public  Property imagen As String
        
        '
        Public  Property fecreg As Date
        
        '
        Public  Property fecmod As Date
        
        Public Sub New()
            
        End Sub
        
        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _idproducto As Integer, ByVal _idunidadmedida As String, ByVal _idcategoria As Integer, ByVal _idusuarios As Integer, ByVal _nombre As String, ByVal _precio1 As Decimal, ByVal _precio2 As Decimal, ByVal _imagen As String, ByVal _fecreg As Date, ByVal _fecmod As Date)
            
            Tipo = _Tipo
            idproducto = _idproducto
            idunidadmedida = _idunidadmedida
            idcategoria = _idcategoria
            idusuarios = _idusuarios
            nombre = _nombre
            precio1 = _precio1
            precio2 = _precio2
            imagen = _imagen
            fecreg = _fecreg
            fecmod = _fecmod
        End Sub
    End Class
End Namespace
