'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_unidadmedida
        
        Public  Property Tipo As Integer
        
        '
        Public  Property idunidadmedida As String
        
        '
        Public  Property nombre As String
        
        Public Sub New()
            
        End Sub
        
        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _idunidadmedida As String, ByVal _nombre As String)
            
            Tipo = _Tipo
            idunidadmedida = _idunidadmedida
            nombre = _nombre
        End Sub
    End Class
End Namespace
