'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_usuarios

        Public Property TipoAccion As Integer

        '
        Public  Property idusuarios As Nullable(of Integer)
        
        '
        Public  Property idpersonas As Nullable(of Integer)
        
        '
        Public  Property user As String
        
        '
        Public  Property password As String
        
        '
        Public  Property perfil As String

        'V vendedor
        'A administrador
        Public  Property tipo As String
        
        '
        Public  Property fecreg As Date
        
        '
        Public  Property fecmod As Date
        
        Public Sub New()
            
        End Sub

        '''asdas
        Public Sub New(ByVal _TipoAccion As Integer, ByVal _idusuarios As Integer, ByVal _idpersonas As Integer, ByVal _user As String, ByVal _password As String, ByVal _perfil As String, ByVal _tipoUsuario As String, ByVal _fecreg As Date, ByVal _fecmod As Date)

            TipoAccion = _tipo
            idusuarios = _idusuarios
            idpersonas = _idpersonas
            user = _user
            password = _password
            perfil = _perfil
            tipo = _tipoUsuario
            fecreg = _fecreg
            fecmod = _fecmod
        End Sub
    End Class
End Namespace
