'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ClaseCodeDOM
    
    Public Class CE_ventas
        
        Public  Property Tipo As Integer
        
        '
        Public  Property idventas As Nullable(of Integer)
        
        '
        Public  Property idusuarios As Nullable(of Integer)
        
        '
        Public  Property idpersonas As Nullable(of Integer)
        
        '03 boletas
        '01 facturas
        Public  Property tipocomprobante As String
        
        '
        Public  Property fechahora As Date
        
        '
        Public  Property serie As String
        
        '
        Public  Property numero As Nullable(of Integer)
        
        '
        Public  Property subtotal As Decimal
        
        '
        Public  Property igv As Decimal
        
        '
        Public  Property descuento As Decimal
        
        '
        Public  Property total As Decimal
        
        Public Sub New()
            
        End Sub
        
        '''asdas
        Public Sub New(ByVal _Tipo As Integer, ByVal _idventas As Integer, ByVal _idusuarios As Integer, ByVal _idpersonas As Integer, ByVal _tipocomprobante As String, ByVal _fechahora As Date, ByVal _serie As String, ByVal _numero As Integer, ByVal _subtotal As Decimal, ByVal _igv As Decimal, ByVal _descuento As Decimal, ByVal _total As Decimal)
            
            Tipo = _Tipo
            idventas = _idventas
            idusuarios = _idusuarios
            idpersonas = _idpersonas
            tipocomprobante = _tipocomprobante
            fechahora = _fechahora
            serie = _serie
            numero = _numero
            subtotal = _subtotal
            igv = _igv
            descuento = _descuento
            total = _total
        End Sub
    End Class
End Namespace
