'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient

Namespace ClaseCodeDOM

    Public Class CD_categoria

        Private cmd As MySqlCommand

        Public Overridable Function SP_categoria(ByVal dts As CE_categoria, ByVal cnn As MySqlConnection) As Boolean
            Try
                cmd = New MySqlCommand("SP_categoria")
                cmd.CommandType = CommandType.StoredProcedure
                cmd.Connection = cnn

                cmd.Parameters.AddWithValue("_Tipo", dts.Tipo) ' = --- BD ---
                cmd.Parameters.AddWithValue("_idcategoria", dts.idcategoria) ' =  --- VALOR PARA idcategoria | 
                cmd.Parameters.AddWithValue("_nombre", dts.nombre) ' =  --- VALOR PARA nombre | 
                If cmd.ExecuteNonQuery Then
                    Return True
                Else
                    Return False
                End If
            Catch ex As Exception
                Return False
            End Try ' =  --- INSTRUCCIONES ---
        End Function

        Public Overridable Function DT_categoria(ByVal dts As CE_categoria, ByVal cnn As MySqlConnection) As DataTable
            Try

                cmd = New MySqlCommand("SP_categoria")
                cmd.CommandType = CommandType.StoredProcedure
                cmd.Connection = cnn
                Dim dt As New DataTable
                Dim da As New MySqlDataAdapter(cmd)


                cmd.Parameters.AddWithValue("_Tipo", dts.Tipo) ' = --- BD ---
                cmd.Parameters.AddWithValue("_idcategoria", dts.idcategoria) ' =  --- VALOR PARA idcategoria | 
                cmd.Parameters.AddWithValue("_nombre", dts.nombre) ' =  --- VALOR PARA nombre | 
                Dim dataReader = cmd.ExecuteReader()


                dt.Load(dataReader) ' =  --- INSTRUCCIONES ---
                dataReader.Close() ' =  cerrando datareader
                Return dt
            Catch ex As Exception
                Return Nothing
            End Try ' =  retorno---
        End Function
    End Class
End Namespace
