'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient

Namespace ClaseCodeDOM

    Public Class CD_cajachica

        Private cmd As MySqlCommand

        Public Overridable Function SP_cajachica(ByVal dts As CE_cajachica, ByVal cnn As MySqlConnection) As Boolean
            Try
                cmd = New MySqlCommand("SP_cajachica")
                cmd.CommandType = CommandType.StoredProcedure
                cmd.Connection = cnn

                cmd.Parameters.AddWithValue("_Tipo", dts.Tipo) ' = --- BD ---
                cmd.Parameters.AddWithValue("_idcajadinero", dts.idcajadinero) ' =  --- VALOR PARA idcajadinero | 
                cmd.Parameters.AddWithValue("_idusuarios", dts.idusuarios) ' =  --- VALOR PARA idusuarios | 
                cmd.Parameters.AddWithValue("_fecha", Convert.ToDateTime(dts.fecha).ToString("yyyy-MM-dd")) ' =  --- VALOR PARA fecha | 
                cmd.Parameters.AddWithValue("_fechaInicio", Convert.ToDateTime(dts.fechaInicio).ToString("yyyy-MM-dd HH:mm:ss")) ' =  --- VALOR PARA fechaInicio | 
                cmd.Parameters.AddWithValue("_fechaFinal", Convert.ToDateTime(dts.fechaFinal).ToString("yyyy-MM-dd HH:mm:ss")) ' =  --- VALOR PARA fechaFinal | 
                cmd.Parameters.AddWithValue("_montoinicio", dts.montoinicio) ' =  --- VALOR PARA montoinicio | 
                cmd.Parameters.AddWithValue("_montofinal", dts.montofinal) ' =  --- VALOR PARA montofinal | 
                cmd.Parameters.AddWithValue("_comentario", dts.comentario) ' =  --- VALOR PARA comentario | 
                If cmd.ExecuteNonQuery Then
                    Return True
                Else
                    Return False
                End If
            Catch ex As Exception
                Return False
            End Try ' =  --- INSTRUCCIONES ---
        End Function

        Public Overridable Function DT_cajachica(ByVal dts As CE_cajachica, ByVal cnn As MySqlConnection) As DataTable
            Try

                cmd = New MySqlCommand("SP_cajachica")
                cmd.CommandType = CommandType.StoredProcedure
                cmd.Connection = cnn
                Dim dt As New DataTable
                Dim da As New MySqlDataAdapter(cmd)


                cmd.Parameters.AddWithValue("_Tipo", dts.Tipo) ' = --- BD ---
                cmd.Parameters.AddWithValue("_idcajadinero", dts.idcajadinero) ' =  --- VALOR PARA idcajadinero | 
                cmd.Parameters.AddWithValue("_idusuarios", dts.idusuarios) ' =  --- VALOR PARA idusuarios | 
                cmd.Parameters.AddWithValue("_fecha", dts.fecha) ' =  --- VALOR PARA fecha | 
                cmd.Parameters.AddWithValue("_fechaInicio", dts.fechaInicio) ' =  --- VALOR PARA fechaInicio | 
                cmd.Parameters.AddWithValue("_fechaFinal", dts.fechaFinal) ' =  --- VALOR PARA fechaFinal | 
                cmd.Parameters.AddWithValue("_montoinicio", dts.montoinicio) ' =  --- VALOR PARA montoinicio | 
                cmd.Parameters.AddWithValue("_montofinal", dts.montofinal) ' =  --- VALOR PARA montofinal | 
                cmd.Parameters.AddWithValue("_comentario", dts.comentario) ' =  --- VALOR PARA comentario | 
                Dim dataReader = cmd.ExecuteReader()


                dt.Load(dataReader) ' =  --- INSTRUCCIONES ---
                dataReader.Close() ' =  cerrando datareader
                Return dt
            Catch ex As Exception
                Return Nothing
            End Try ' =  retorno---
        End Function
    End Class
End Namespace
