'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient

Namespace ClaseCodeDOM
    
    Public Class CD_dinero
        
        Private cmd As MySqlCommand
        
        Public Overridable Function SP_dinero(ByVal dts As CE_dinero, ByVal cnn As MySqlConnection) As Boolean
            Try
cmd = New MySqlCommand("SP_dinero")
cmd.CommandType = CommandType.StoredProcedure
cmd.Connection = cnn

cmd.Parameters.AddWithValue("_Tipo",dts.Tipo)' = --- BD ---
            cmd.Parameters.AddWithValue("_iddinero", dts.iddinero) ' =  --- VALOR PARA iddinero | 
            cmd.Parameters.AddWithValue("_idusuarios", dts.idusuarios) ' =  --- VALOR PARA idusuarios | 
            cmd.Parameters.AddWithValue("_idventas", dts.idventas) ' =  --- VALOR PARA idventas | 
                cmd.Parameters.AddWithValue("_compraventa", dts.compraventa) ' =  --- VALOR PARA compraventa | C compra
                'V venta
                cmd.Parameters.AddWithValue("_fechahora", dts.fechahora) ' =  --- VALOR PARA fechahora | 
                cmd.Parameters.AddWithValue("_tipopago", dts.tipopago) ' =  --- VALOR PARA tipopago | E efectivo
                'Q qr
                cmd.Parameters.AddWithValue("_monto", dts.monto) ' =  --- VALOR PARA monto | 
                If cmd.ExecuteNonQuery Then
                    Return True
                Else
                    Return False
                End If
            Catch ex As Exception
                Return False
            End Try ' =  --- INSTRUCCIONES ---
        End Function

        Public Overridable Function DT_dinero(ByVal dts As CE_dinero, ByVal cnn As MySqlConnection) As DataTable
            Try

                cmd = New MySqlCommand("SP_dinero")
                cmd.CommandType = CommandType.StoredProcedure
                cmd.Connection = cnn
                Dim dt As New DataTable
                Dim da As New MySqlDataAdapter(cmd)


                cmd.Parameters.AddWithValue("_Tipo", dts.Tipo) ' = --- BD ---
                cmd.Parameters.AddWithValue("_iddinero", dts.iddinero) ' =  --- VALOR PARA iddinero | 
                cmd.Parameters.AddWithValue("_idusuarios", dts.idusuarios) ' =  --- VALOR PARA idusuarios | 
                cmd.Parameters.AddWithValue("_idventas", dts.idventas) ' =  --- VALOR PARA idventas | 
                cmd.Parameters.AddWithValue("_compraventa", dts.compraventa) ' =  --- VALOR PARA compraventa | C compra
                'V venta
                cmd.Parameters.AddWithValue("_fechahora", dts.fechahora) ' =  --- VALOR PARA fechahora | 
                cmd.Parameters.AddWithValue("_tipopago", dts.tipopago) ' =  --- VALOR PARA tipopago | E efectivo
                'Q qr
                cmd.Parameters.AddWithValue("_monto", dts.monto) ' =  --- VALOR PARA monto | 
                Dim dataReader = cmd.ExecuteReader()


                dt.Load(dataReader) ' =  --- INSTRUCCIONES ---
                dataReader.Close() ' =  cerrando datareader
                Return dt
            Catch ex As Exception
                Return Nothing
            End Try' =  retorno---
        End Function
    End Class
End Namespace
