'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient

Namespace ClaseCodeDOM

    Public Class CD_productostock

        Private cmd As MySqlCommand

        Public Overridable Function SP_productostock(ByVal dts As CE_productostock, ByVal cnn As MySqlConnection) As Boolean
            Try
                cmd = New MySqlCommand("SP_productostock")
                cmd.CommandType = CommandType.StoredProcedure
                cmd.Connection = cnn

                cmd.Parameters.AddWithValue("_Tipo", dts.Tipo) ' = --- BD ---
                cmd.Parameters.AddWithValue("_idproductostock", dts.idproductostock) ' =  --- VALOR PARA idproductostock | 
                cmd.Parameters.AddWithValue("_idproducto", dts.idproducto) ' =  --- VALOR PARA idproducto | 
                cmd.Parameters.AddWithValue("_idusuarios", dts.idusuarios) ' =  --- VALOR PARA idusuarios | 
                cmd.Parameters.AddWithValue("_fechahora", dts.fechahora) ' =  --- VALOR PARA fechahora | 
                cmd.Parameters.AddWithValue("_entrada", dts.entrada) ' =  --- VALOR PARA entrada | 
                cmd.Parameters.AddWithValue("_salida", dts.salida) ' =  --- VALOR PARA salida | 
                cmd.Parameters.AddWithValue("_total", dts.total) ' =  --- VALOR PARA total | 
                cmd.Parameters.AddWithValue("_comentario", dts.comentario) ' =  --- VALOR PARA comentario | 
                If cmd.ExecuteNonQuery Then
                    Return True
                Else
                    Return False
                End If
            Catch ex As Exception
                Return False
            End Try ' =  --- INSTRUCCIONES ---
        End Function

        Public Overridable Function DT_productostock(ByVal dts As CE_productostock, ByVal cnn As MySqlConnection) As DataTable
            Try

                cmd = New MySqlCommand("SP_productostock")
                cmd.CommandType = CommandType.StoredProcedure
                cmd.Connection = cnn
                Dim dt As New DataTable
                Dim da As New MySqlDataAdapter(cmd)


                cmd.Parameters.AddWithValue("_Tipo", dts.Tipo) ' = --- BD ---
                cmd.Parameters.AddWithValue("_idproductostock", dts.idproductostock) ' =  --- VALOR PARA idproductostock | 
                cmd.Parameters.AddWithValue("_idproducto", dts.idproducto) ' =  --- VALOR PARA idproducto | 
                cmd.Parameters.AddWithValue("_idusuarios", dts.idusuarios) ' =  --- VALOR PARA idusuarios | 
                cmd.Parameters.AddWithValue("_fechahora", dts.fechahora) ' =  --- VALOR PARA fechahora | 
                cmd.Parameters.AddWithValue("_entrada", dts.entrada) ' =  --- VALOR PARA entrada | 
                cmd.Parameters.AddWithValue("_salida", dts.salida) ' =  --- VALOR PARA salida | 
                cmd.Parameters.AddWithValue("_total", dts.total) ' =  --- VALOR PARA total | 
                cmd.Parameters.AddWithValue("_comentario", dts.comentario) ' =  --- VALOR PARA comentario | 
                Dim dataReader = cmd.ExecuteReader()


                dt.Load(dataReader) ' =  --- INSTRUCCIONES ---
                dataReader.Close() ' =  cerrando datareader
                Return dt
            Catch ex As Exception
                Return Nothing
            End Try ' =  retorno---
        End Function
    End Class
End Namespace
