'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient

Namespace ClaseCodeDOM

    Public Class CD_pedido

        Private cmd As MySqlCommand

        Public Overridable Function SP_pedido(ByVal dts As CE_pedido, ByVal cnn As MySqlConnection) As Boolean
            Try
                cmd = New MySqlCommand("SP_pedido")
                cmd.CommandType = CommandType.StoredProcedure
                cmd.Connection = cnn

                cmd.Parameters.AddWithValue("_Tipo", dts.Tipo) ' = --- BD ---
                cmd.Parameters.AddWithValue("_idpedido", dts.idpedido) ' =  --- VALOR PARA idpedido | 
                cmd.Parameters.AddWithValue("_idmesa", dts.idmesa) ' =  --- VALOR PARA idmesa | 
                cmd.Parameters.AddWithValue("_idpersonas", dts.idpersonas) ' =  --- VALOR PARA idpersonas | 
                cmd.Parameters.AddWithValue("_idusuarios", dts.idusuarios) ' =  --- VALOR PARA idusuarios | 
                cmd.Parameters.AddWithValue("_numero", dts.numero) ' =  --- VALOR PARA numero | 
                cmd.Parameters.AddWithValue("_total", dts.total) ' =  --- VALOR PARA total | 
                cmd.Parameters.AddWithValue("_fechahora", Convert.ToDateTime(dts.fechahora).ToString("yyyy-MM-dd HH:mm:ss")) ' =  --- VALOR PARA fechahora | 
                cmd.Parameters.AddWithValue("_estado", dts.estado) ' =  --- VALOR PARA estado | 0 cancelado
                '1 activo
                '2 canjeado a comprobante
                If cmd.ExecuteNonQuery Then
                    Return True
                Else
                    Return False
                End If
            Catch ex As Exception
                Return False
            End Try ' =  --- INSTRUCCIONES ---
        End Function

        Public Overridable Function DT_pedido(ByVal dts As CE_pedido, ByVal cnn As MySqlConnection) As DataTable
            Try

                cmd = New MySqlCommand("SP_pedido")
                cmd.CommandType = CommandType.StoredProcedure
                cmd.Connection = cnn
                Dim dt As New DataTable
                Dim da As New MySqlDataAdapter(cmd)


                cmd.Parameters.AddWithValue("_Tipo", dts.Tipo) ' = --- BD ---
                cmd.Parameters.AddWithValue("_idpedido", dts.idpedido) ' =  --- VALOR PARA idpedido | 
                cmd.Parameters.AddWithValue("_idmesa", dts.idmesa) ' =  --- VALOR PARA idmesa | 
                cmd.Parameters.AddWithValue("_idpersonas", dts.idpersonas) ' =  --- VALOR PARA idpersonas | 
                cmd.Parameters.AddWithValue("_idusuarios", dts.idusuarios) ' =  --- VALOR PARA idusuarios | 
                cmd.Parameters.AddWithValue("_numero", dts.numero) ' =  --- VALOR PARA numero | 
                cmd.Parameters.AddWithValue("_total", dts.total) ' =  --- VALOR PARA total | 
                cmd.Parameters.AddWithValue("_fechahora", Convert.ToDateTime(dts.fechahora).ToString("yyyy-MM-dd HH:mm:ss")) ' =  --- VALOR PARA fechahora | 
                cmd.Parameters.AddWithValue("_estado", dts.estado) ' =  --- VALOR PARA estado | 0 cancelado
                '1 activo
                '2 canjeado a comprobante
                Dim dataReader = cmd.ExecuteReader()


                dt.Load(dataReader) ' =  --- INSTRUCCIONES ---
                dataReader.Close() ' =  cerrando datareader
                Return dt
            Catch ex As Exception
                Return Nothing
            End Try ' =  retorno---
        End Function
    End Class
End Namespace
