'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM
    
    Public Class Transaccion_categoria
        Inherits Conexion
        
        Private cmd As MySqlCommand
        
        Public Overridable Function SP_categoria(ByVal CE_categoria As CE_categoria) As Boolean
            
Dim boolcategoria as Boolean
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_categoria as new cd_categoria' =  ----------------------DEFINE categoria ---------------
            boolcategoria = CD_categoria.SP_categoria(CE_categoria, conexion)' =  ---------------------- VALOR PARA categoria ---------------
                   
if boolcategoria then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return boolvalidador
Catch ex As Exception
boolvalidador = false
return boolvalidador
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
        
        Public Overridable Function DT_categoria(ByVal CE_categoria As CE_categoria) As DataTable
            
Dim dtcategoria as new DataTable
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_categoria as new cd_categoria' =  ----------------------DEFINE categoria ---------------
            dtcategoria = CD_categoria.DT_categoria(CE_categoria, conexion)' =  ---------------------- VALOR PARA categoria ---------------
                   
if dtcategoria.rows.count > 0 then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return dtcategoria
Catch ex As Exception
boolvalidador = false
'return  dtcategoria
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
