'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM
    
    Public Class Transaccion_personas
        Inherits Conexion
        
        Private cmd As MySqlCommand
        
        Public Overridable Function SP_personas(ByVal CE_personas As CE_personas) As Boolean
            
Dim boolpersonas as Boolean
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_personas as new cd_personas' =  ----------------------DEFINE personas ---------------
            boolpersonas = CD_personas.SP_personas(CE_personas, conexion)' =  ---------------------- VALOR PARA personas ---------------
                   
if boolpersonas then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return boolvalidador
Catch ex As Exception
boolvalidador = false
return boolvalidador
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
        
        Public Overridable Function DT_personas(ByVal CE_personas As CE_personas) As DataTable
            
Dim dtpersonas as new DataTable
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_personas as new cd_personas' =  ----------------------DEFINE personas ---------------
            dtpersonas = CD_personas.DT_personas(CE_personas, conexion)' =  ---------------------- VALOR PARA personas ---------------
                   
if dtpersonas.rows.count > 0 then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return dtpersonas
Catch ex As Exception
boolvalidador = false
'return  dtpersonas
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
