'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM

    Public Class Transaccion_lectura
        Inherits Conexion
        Private cmd As MySqlCommand

        Public Overridable Function DT_leer(ByVal CE_dgv As CE_dgv) As DataTable
            Dim dtleer As New DataTable
            Dim boolvalidador As Boolean
            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim CD_lectura As New CD_lectura ' =  ----------------------DEFINE kardex ---------------
                        dtleer = CD_lectura.SP_DatagridView(CE_dgv, conexion) ' =  ---------------------- VALOR PARA kardex ---------------
                        boolvalidador = True
                        Scope.Complete()
                        Return dtleer
                    Catch ex As Exception

                        boolvalidador = False
                        Return Nothing
                    Finally
                        conexion.Close()
                    End Try
                End Using
            End Using
        End Function
    End Class
End Namespace
