'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM
    
    Public Class Transaccion_dinero
        Inherits Conexion
        
        Private cmd As MySqlCommand
        
        Public Overridable Function SP_dinero(ByVal CE_dinero As CE_dinero) As Boolean
            
Dim booldinero as Boolean
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_dinero as new cd_dinero' =  ----------------------DEFINE dinero ---------------
            booldinero = CD_dinero.SP_dinero(CE_dinero, conexion)' =  ---------------------- VALOR PARA dinero ---------------
                   
if booldinero then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return boolvalidador
Catch ex As Exception
boolvalidador = false
return boolvalidador
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
        
        Public Overridable Function DT_dinero(ByVal CE_dinero As CE_dinero) As DataTable
            
Dim dtdinero as new DataTable
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_dinero as new cd_dinero' =  ----------------------DEFINE dinero ---------------
            dtdinero = CD_dinero.DT_dinero(CE_dinero, conexion)' =  ---------------------- VALOR PARA dinero ---------------
                   
if dtdinero.rows.count > 0 then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return dtdinero
Catch ex As Exception
boolvalidador = false
'return  dtdinero
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
