'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM
    
    Public Class Transaccion_usuarios
        Inherits Conexion
        
        Private cmd As MySqlCommand
        
        Public Overridable Function SP_usuarios(ByVal CE_usuarios As CE_usuarios) As Boolean
            
Dim boolusuarios as Boolean
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_usuarios as new cd_usuarios' =  ----------------------DEFINE usuarios ---------------
            boolusuarios = CD_usuarios.SP_usuarios(CE_usuarios, conexion)' =  ---------------------- VALOR PARA usuarios ---------------
                   
if boolusuarios then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return boolvalidador
Catch ex As Exception
boolvalidador = false
return boolvalidador
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
        
        Public Overridable Function DT_usuarios(ByVal CE_usuarios As CE_usuarios) As DataTable
            
Dim dtusuarios as new DataTable
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_usuarios as new cd_usuarios' =  ----------------------DEFINE usuarios ---------------
            dtusuarios = CD_usuarios.DT_usuarios(CE_usuarios, conexion)' =  ---------------------- VALOR PARA usuarios ---------------
                   
if dtusuarios.rows.count > 0 then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return dtusuarios
Catch ex As Exception
boolvalidador = false
'return  dtusuarios
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
