'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM
    
    Public Class Transaccion_ventas
        Inherits Conexion
        
        Private cmd As MySqlCommand
        
        Public Overridable Function SP_ventas(ByVal CE_ventas As CE_ventas) As Boolean
            
Dim boolventas as Boolean
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_ventas as new cd_ventas' =  ----------------------DEFINE ventas ---------------
            boolventas = CD_ventas.SP_ventas(CE_ventas, conexion)' =  ---------------------- VALOR PARA ventas ---------------
                   
if boolventas then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return boolvalidador
Catch ex As Exception
boolvalidador = false
return boolvalidador
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
        
        Public Overridable Function DT_ventas(ByVal CE_ventas As CE_ventas) As DataTable
            
Dim dtventas as new DataTable
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_ventas as new cd_ventas' =  ----------------------DEFINE ventas ---------------
            dtventas = CD_ventas.DT_ventas(CE_ventas, conexion)' =  ---------------------- VALOR PARA ventas ---------------
                   
if dtventas.rows.count > 0 then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return dtventas
Catch ex As Exception
boolvalidador = false
'return  dtventas
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
