'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM

    Public Class Transaccion_empresa
        Inherits Conexion

        Private cmd As MySqlCommand

        Public Overridable Function SP_empresa(ByVal CE_empresa As CE_empresa) As Boolean

            Dim boolempresa As Boolean
            Dim boolvalidador As Boolean

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim cd_empresa As New CD_empresa ' =  ----------------------DEFINE empresa ---------------
                        boolempresa = cd_empresa.SP_empresa(CE_empresa, conexion) ' =  ---------------------- VALOR PARA empresa ---------------

                        If boolempresa Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return boolvalidador
                    Catch ex As Exception
                        boolvalidador = False
                        Return boolvalidador
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function

        Public Overridable Function DT_empresa(ByVal CE_empresa As CE_empresa) As DataTable

            Dim dtempresa As New DataTable
            Dim boolvalidador As Boolean

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim cd_empresa As New CD_empresa ' =  ----------------------DEFINE empresa ---------------
                        dtempresa = cd_empresa.DT_empresa(CE_empresa, conexion) ' =  ---------------------- VALOR PARA empresa ---------------

                        If dtempresa.Rows.Count > 0 Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return dtempresa
                    Catch ex As Exception
                        boolvalidador = False
                        'return  dtempresa
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
