'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM

    Public Class Transaccion_productostock
        Inherits Conexion

        Private cmd As MySqlCommand

        Public Overridable Function SP_productostock(ByVal CE_productostock As CE_productostock) As Boolean

            Dim boolproductostock As Boolean
            Dim boolvalidador As Boolean

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim cd_productostock As New CD_productostock ' =  ----------------------DEFINE productostock ---------------
                        boolproductostock = cd_productostock.SP_productostock(CE_productostock, conexion) ' =  ---------------------- VALOR PARA productostock ---------------

                        If boolproductostock Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return boolvalidador
                    Catch ex As Exception
                        boolvalidador = False
                        Return boolvalidador
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function

        Public Overridable Function DT_productostock(ByVal CE_productostock As CE_productostock) As DataTable

            Dim dtproductostock As New DataTable
            Dim boolvalidador As Boolean

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim cd_productostock As New CD_productostock ' =  ----------------------DEFINE productostock ---------------
                        dtproductostock = cd_productostock.DT_productostock(CE_productostock, conexion) ' =  ---------------------- VALOR PARA productostock ---------------

                        If dtproductostock.Rows.Count > 0 Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return dtproductostock
                    Catch ex As Exception
                        boolvalidador = False
                        'return  dtproductostock
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
