'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM
    
    Public Class Transaccion_cajachica
        Inherits Conexion
        
        Private cmd As MySqlCommand
        
        Public Overridable Function SP_cajachica(ByVal CE_cajachica As CE_cajachica) As Boolean
            
Dim boolcajachica as Boolean
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_cajachica as new cd_cajachica' =  ----------------------DEFINE cajachica ---------------
            boolcajachica = CD_cajachica.SP_cajachica(CE_cajachica, conexion)' =  ---------------------- VALOR PARA cajachica ---------------
                   
if boolcajachica then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return boolvalidador
Catch ex As Exception
boolvalidador = false
return boolvalidador
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
        
        Public Overridable Function DT_cajachica(ByVal CE_cajachica As CE_cajachica) As DataTable
            
Dim dtcajachica as new DataTable
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_cajachica as new cd_cajachica' =  ----------------------DEFINE cajachica ---------------
            dtcajachica = CD_cajachica.DT_cajachica(CE_cajachica, conexion)' =  ---------------------- VALOR PARA cajachica ---------------
                   
if dtcajachica.rows.count > 0 then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return dtcajachica
Catch ex As Exception
boolvalidador = false
'return  dtcajachica
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
