'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM
    
    Public Class Transaccion_unidadmedida
        Inherits Conexion
        
        Private cmd As MySqlCommand
        
        Public Overridable Function SP_unidadmedida(ByVal CE_unidadmedida As CE_unidadmedida) As Boolean
            
Dim boolunidadmedida as Boolean
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_unidadmedida as new cd_unidadmedida' =  ----------------------DEFINE unidadmedida ---------------
            boolunidadmedida = CD_unidadmedida.SP_unidadmedida(CE_unidadmedida, conexion)' =  ---------------------- VALOR PARA unidadmedida ---------------
                   
if boolunidadmedida then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return boolvalidador
Catch ex As Exception
boolvalidador = false
return boolvalidador
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
        
        Public Overridable Function DT_unidadmedida(ByVal CE_unidadmedida As CE_unidadmedida) As DataTable
            
Dim dtunidadmedida as new DataTable
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_unidadmedida as new cd_unidadmedida' =  ----------------------DEFINE unidadmedida ---------------
            dtunidadmedida = CD_unidadmedida.DT_unidadmedida(CE_unidadmedida, conexion)' =  ---------------------- VALOR PARA unidadmedida ---------------
                   
if dtunidadmedida.rows.count > 0 then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return dtunidadmedida
Catch ex As Exception
boolvalidador = false
'return  dtunidadmedida
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
