'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM

    Public Class Transaccion_pedido
        Inherits Conexion

        Private cmd As MySqlCommand

        Public Overridable Function SP_pedido(ByVal CE_pedido As CE_pedido) As Boolean

            Dim boolpedido As Boolean
            Dim boolvalidador As Boolean

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim cd_pedido As New CD_pedido ' =  ----------------------DEFINE pedido ---------------
                        boolpedido = cd_pedido.SP_pedido(CE_pedido, conexion) ' =  ---------------------- VALOR PARA pedido ---------------

                        If boolpedido Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return boolvalidador
                    Catch ex As Exception
                        boolvalidador = False
                        Return boolvalidador
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function

        Public Overridable Function DT_pedido(ByVal CE_pedido As CE_pedido) As DataTable

            Dim dtpedido As New DataTable
            Dim boolvalidador As Boolean

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim cd_pedido As New CD_pedido ' =  ----------------------DEFINE pedido ---------------
                        dtpedido = cd_pedido.DT_pedido(CE_pedido, conexion) ' =  ---------------------- VALOR PARA pedido ---------------

                        If dtpedido.Rows.Count > 0 Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return dtpedido
                    Catch ex As Exception
                        boolvalidador = False
                        'return  dtpedido
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function


        Public Overridable Function SP_ventas(ByVal CE_personas As CE_personas, ByVal CE_pedido As CE_pedido, ByVal ListaCE_detallepedido As List(Of CE_detallepedido), ByVal ListaCE_productostock As List(Of CE_productostock)) As Boolean
            Dim dt_personas As New DataTable
            Dim dt_pedido As New DataTable

            Dim id_personas As Integer = Nothing
            Dim id_pedido As Integer = Nothing

            Dim boolventas_compras As Integer = 1
            Dim boolvalidador As Boolean
            Dim con As New Conexion
            Dim my As New MySqlConnection

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try

                        conexion.Open() ' = ABRIENDO CONEXION

                        Dim CD_personas As New CD_personas
                        Dim CD_pedido As New CD_pedido
                        Dim CD_detallepedido As New CD_detallepedido
                        Dim CD_productostock As New CD_productostock

                        If CE_personas.idpersonas = 0 Then
                            dt_personas = CD_personas.DT_personas(CE_personas, conexion)
                            id_personas = CType(dt_personas.Rows(0).Item("idpersonas").ToString, Integer)
                            boolventas_compras = 1
                        ElseIf CE_personas.idpersonas = 2 Then
                            id_personas = CE_personas.idpersonas
                        Else
                            CE_personas.Tipo = 6
                            CD_personas.SP_personas(CE_personas, conexion)
                            id_personas = CE_personas.idpersonas
                        End If

                        CE_pedido.idpersonas = id_personas
                        dt_pedido = CD_pedido.DT_pedido(CE_pedido, conexion)
                        id_pedido = CType(dt_pedido.Rows(0).Item("idpedido").ToString, Integer)

                        For Each item As CE_detallepedido In ListaCE_detallepedido
                            CD_detallepedido = New CD_detallepedido
                            item.pedido_idpedido = id_pedido
                            If CD_detallepedido.SP_detallepedido(item, conexion) Then boolventas_compras *= 1 Else boolventas_compras *= 0
                        Next

                        For Each item As CE_productostock In ListaCE_productostock
                            CD_productostock = New CD_productostock
                            If CD_productostock.SP_productostock(item, conexion) Then boolventas_compras *= 1 Else boolventas_compras *= 0
                        Next


                        If boolventas_compras = 1 Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return boolvalidador
                        conexion.Close()
                    Catch ex As Exception
                        boolvalidador = False
                        Return boolvalidador
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function


    End Class
End Namespace
