'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM

    Public Class Transaccion_personas
        Inherits Conexion

        Private cmd As MySqlCommand

        Public Overridable Function SP_personas(ByVal CE_personas As CE_personas) As Boolean

            Dim boolpersonas As Boolean
            Dim boolvalidador As Boolean

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim cd_personas As New CD_personas ' =  ----------------------DEFINE personas ---------------
                        boolpersonas = cd_personas.SP_personas(CE_personas, conexion) ' =  ---------------------- VALOR PARA personas ---------------

                        If boolpersonas Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return boolvalidador
                    Catch ex As Exception
                        boolvalidador = False
                        Return boolvalidador
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function

        Public Overridable Function DT_personas(ByVal CE_personas As CE_personas) As DataTable

            Dim dtpersonas As New DataTable
            Dim boolvalidador As Boolean

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim cd_personas As New CD_personas ' =  ----------------------DEFINE personas ---------------
                        dtpersonas = cd_personas.DT_personas(CE_personas, conexion) ' =  ---------------------- VALOR PARA personas ---------------

                        If dtpersonas.Rows.Count > 0 Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return dtpersonas
                    Catch ex As Exception
                        boolvalidador = False
                        'return  dtpersonas
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
