'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM
    
    Public Class Transaccion_pedido
        Inherits Conexion
        
        Private cmd As MySqlCommand
        
        Public Overridable Function SP_pedido(ByVal CE_pedido As CE_pedido) As Boolean
            
Dim boolpedido as Boolean
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_pedido as new cd_pedido' =  ----------------------DEFINE pedido ---------------
            boolpedido = CD_pedido.SP_pedido(CE_pedido, conexion)' =  ---------------------- VALOR PARA pedido ---------------
                   
if boolpedido then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return boolvalidador
Catch ex As Exception
boolvalidador = false
return boolvalidador
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
        
        Public Overridable Function DT_pedido(ByVal CE_pedido As CE_pedido) As DataTable
            
Dim dtpedido as new DataTable
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_pedido as new cd_pedido' =  ----------------------DEFINE pedido ---------------
            dtpedido = CD_pedido.DT_pedido(CE_pedido, conexion)' =  ---------------------- VALOR PARA pedido ---------------
                   
if dtpedido.rows.count > 0 then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return dtpedido
Catch ex As Exception
boolvalidador = false
'return  dtpedido
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
