'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM
    
    Public Class Transaccion_productostock
        Inherits Conexion
        
        Private cmd As MySqlCommand
        
        Public Overridable Function SP_productostock(ByVal CE_productostock As CE_productostock) As Boolean
            
Dim boolproductostock as Boolean
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_productostock as new cd_productostock' =  ----------------------DEFINE productostock ---------------
            boolproductostock = CD_productostock.SP_productostock(CE_productostock, conexion)' =  ---------------------- VALOR PARA productostock ---------------
                   
if boolproductostock then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return boolvalidador
Catch ex As Exception
boolvalidador = false
return boolvalidador
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
        
        Public Overridable Function DT_productostock(ByVal CE_productostock As CE_productostock) As DataTable
            
Dim dtproductostock as new DataTable
Dim boolvalidador as Boolean

Using Scope As New TransactionScope()
       Using conexion As New MySqlConnection(conexion_base)
try
       conexion.Open() ' = ABRIENDO CONEXION
            Dim cd_productostock as new cd_productostock' =  ----------------------DEFINE productostock ---------------
            dtproductostock = CD_productostock.DT_productostock(CE_productostock, conexion)' =  ---------------------- VALOR PARA productostock ---------------
                   
if dtproductostock.rows.count > 0 then    
boolvalidador = true
Scope.Complete()
else
boolvalidador = false
end if
return dtproductostock
Catch ex As Exception
boolvalidador = false
'return  dtproductostock
Finally
 conexion.Close()
 End Try
End Using

       End Using
 
      ' =  ------------ INSTRUCCIONES ------------
        End Function
    End Class
End Namespace
