'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CapaDatos.ClaseCodeDOM
Imports CapaEntidades.ClaseCodeDOM
Imports MySql.Data.MySqlClient
Imports System.Transactions

Namespace ClaseCodeDOM

    Public Class Transaccion_ventas
        Inherits Conexion

        Private cmd As MySqlCommand

        Public Overridable Function SP_ventas(ByVal CE_ventas As CE_ventas) As Boolean

            Dim boolventas As Boolean
            Dim boolvalidador As Boolean

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim cd_ventas As New CD_ventas ' =  ----------------------DEFINE ventas ---------------
                        boolventas = cd_ventas.SP_ventas(CE_ventas, conexion) ' =  ---------------------- VALOR PARA ventas ---------------

                        If boolventas Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return boolvalidador
                    Catch ex As Exception
                        boolvalidador = False
                        Return boolvalidador
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function

        Public Overridable Function DT_ventas(ByVal CE_ventas As CE_ventas) As DataTable

            Dim dtventas As New DataTable
            Dim boolvalidador As Boolean

            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION
                        Dim cd_ventas As New CD_ventas ' =  ----------------------DEFINE ventas ---------------
                        dtventas = cd_ventas.DT_ventas(CE_ventas, conexion) ' =  ---------------------- VALOR PARA ventas ---------------

                        If dtventas.Rows.Count > 0 Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return dtventas
                    Catch ex As Exception
                        boolvalidador = False
                        'return  dtventas
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function


        Public Overridable Function SP_CanjeVentas(Ce_Pedidos As CE_pedido, Ce_Ventas As CE_ventas, listaDetalleVenta As List(Of CE_detalleventas), ce_dinero As CE_dinero) As Boolean

            Dim boolventas As Integer = 1
            Dim boolvalidador As Boolean
            Dim dtventa As New DataTable
            Dim idventa As Integer
            Using Scope As New TransactionScope()
                Using conexion As New MySqlConnection(conexion_base)
                    Try
                        conexion.Open() ' = ABRIENDO CONEXION

                        Dim cdpedidos As New CD_pedido
                        If cdpedidos.SP_pedido(Ce_Pedidos, conexion) Then boolventas *= 1 Else boolventas *= 0

                        Dim cd_ventas As New CD_ventas ' =  ----------------------DEFINE ventas ---------------
                        dtventa = cd_ventas.DT_ventas(Ce_Ventas, conexion)
                        Ce_Ventas.numero = CInt(dtventa.Rows(0).Item("numero"))
                        idventa = CInt(dtventa.Rows(0).Item("idventas"))

                        For Each item As CE_detalleventas In listaDetalleVenta
                            Dim CD_detalleventas As New CD_detalleventas
                            item.ventas_idventas = idventa
                            If CD_detalleventas.SP_detalleventas(item, conexion) Then boolventas *= 1 Else boolventas *= 0
                        Next

                        Dim cfd As New CD_dinero
                        If cfd.SP_dinero(ce_dinero, conexion) Then boolventas *= 1 Else boolventas *= 0

                        If boolventas = 1 Then
                            boolvalidador = True
                            Scope.Complete()
                        Else
                            boolvalidador = False
                        End If
                        Return boolvalidador
                        conexion.Close()
                    Catch ex As Exception
                        boolvalidador = False
                        Return boolvalidador
                    Finally
                        conexion.Close()
                    End Try
                End Using

            End Using

            ' =  ------------ INSTRUCCIONES ------------
        End Function

    End Class
End Namespace
